# STEP_1 Dependencies
FROM node:21-alpine3.19 as deps
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

# STEP_2 Builder: build the app
FROM node:21-alpine3.19 as build
WORKDIR /usr/src/app
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .
RUN npm run build
RUN npm ci -f --only=production && npm cache clean --force

FROM node:21-alpine3.19 as prod
WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/seed-data ./seed-data
COPY --from=build /usr/src/app/uploads ./uploads
COPY --from=build /usr/src/app/public ./public

ENV NODE_ENV=production
USER node
EXPOSE 4000
CMD ["sh", "-c", "npx typeorm migration:run -d dist/db/typeorm.config.js && node dist/main.js"]
