export enum ActionOverEntity {
  NOTE = 'nota',
  CREATED = 'creado',
  COPIED = 'copiada',
  EDITED = 'editado',
  SENT = 'enviado',
  ACCEPTED = 'aceptado',
  DECLINED = 'rechazado',
  INVOICED = 'facturado',
  REMOVED = 'removido',
  RECEIVED = 'recibido',
  VIEWED = 'visto',
  ADDED = 'agregado',
  CHANGE_STATUS = 'cambio_estado',
  APPROVED = 'aprobada',
  AWAITING_FOR_APPROVAL = 'esperando_a_ser_aprobada',
  BILLED = 'pagada',
}
